/* ===== 知识库样本数据 =====
   此文件由每日9:00自动采集任务更新
   手动编辑后刷新页面即可生效
   更新日期：2026-07-30
*/

const KNOWLEDGE_DATA = {
  // ===== 韩语学习 =====
  // 每天 5 句 + 10 个日常单词，120 句覆盖：日常问候 / 自我表达 / 情感 / 职场 / 学习 / 旅行 / 食物 / 数字 / 时间
  // 120 句 ÷ 5 句/天 = 24 天一个内容池，配合单词每天滚动复习
  korean: [
    // === 01-20 日常问候 ===
    { id:"kr01", ko:"안녕하세요.", zh:"您好。", pron:"annyeonghaseyo", grammar:"最常用的问候语，对陌生人/长辈/上级都适用。'안녕'是平安，'하세요'是敬语。回应用同样的 '안녕하세요' 即可。" },
    { id:"kr02", ko:"감사합니다.", zh:"谢谢。", pron:"kamsahamnida", grammar:"正式致谢。'감사'(感谢) + '합니다'(敬语动词)。熟人之间可说 '고마워' (gomawo) 随意语。" },
    { id:"kr03", ko:"죄송합니다.", zh:"对不起。/ 抱歉。", pron:"joesonghamnida", grammar:"正式道歉。'죄송'(抱歉) + '합니다'(敬语)。对平辈可说 '미안해' (mianhae)。" },
    { id:"kr04", ko:"잘 부탁드립니다.", zh:"请多多关照。", pron:"jal butakdeurimnida", grammar:"初次见面/拜托他人时的礼貌用语。直译是「请好好拜托您」，实际是「请多关照」。职场/商务高频。" },
    { id:"kr05", ko:"안녕히 가세요.", zh:"请慢走。（送别）", pron:"annyeonghi gaseyo", grammar:"客人/对方离开时说的话。'안녕히'(平安地) + '가세요'(请走)。对离开的人用。" },
    { id:"kr06", ko:"안녕히 주무세요.", zh:"晚安。", pron:"annyeonghi jumuseyo", grammar:"晚上睡前对人说。'주무세요'是「请睡」的敬语。如果是早安，用 '좋은 아침입니다' (joeun achimimnida)。" },
    { id:"kr07", ko:"만나서 반가워요.", zh:"见到您很高兴。", pron:"mannaseo bangawo", grammar:"初次见面用。'만나서'(见到) + '반가워요'(高兴)。再加 '잘 부탁드립니다' 是标准初次见面寒暄。" },
    { id:"kr08", ko:"오랜만이에요.", zh:"好久不见。", pron:"oraenmanieyo", grammar:"再次见面时用。'오랜만'(很久) + '이에요'(是)。问对方近况：'잘 지내셨어요?'(过得还好吗？)" },
    { id:"kr09", ko:"잘 지내세요?", zh:"您过得好吗？", pron:"jal jinaeseyo", grammar:"日常问候对方近况。'잘'(好好地) + '지내세요'(过)。回答 '네, 잘 지내요'(嗯，过得很好)。" },
    { id:"kr10", ko:"좋은 하루 되세요.", zh:"祝您有美好的一天。", pron:"joeun haru doeseyo", grammar:"日常祝福语。'좋은'(好的) + '하루'(一天) + '되세요'(成为)。早上/白天皆可。" },
    { id:"kr11", ko:"수고하셨습니다.", zh:"辛苦了。", pron:"sugohasyeosseumnida", grammar:"对完成工作的人说。'수고'(辛苦) + '하셨습니다'(做过了)。'수고하세요' 则是对「即将开始工作」的人说。" },
    { id:"kr12", ko:"괜찮아요.", zh:"没关系。/ 没事。", pron:"gwaenchana", grammar:"日常万能句。'괜찮다'(没关系/还不错) + '아요'(随意敬语)。道歉时的回应 '괜찮아요, 신경 쓰지 마세요'(没关系，别在意)。" },
    { id:"kr13", ko:"네, 알겠습니다.", zh:"好的，我知道了。", pron:"ne, algesseumnida", grammar:"正式回应。'네'(是) + '알겠습니다'(知道了)。比 '네' 单字更礼貌。" },
    { id:"kr14", ko:"잘 모르겠어요.", zh:"我不太清楚。", pron:"jal moreugesseoyo", grammar:"礼貌表达不知道。'잘'(完全) + '모르겠어요'(不知道)。'모르다'(不知道)。" },
    { id:"kr15", ko:"천천히 말해 주세요.", zh:"请慢点说。", pron:"cheoncheonhi malhae juseyo", grammar:"听不清时请求对方重复。'천천히'(慢慢地) + '말해 주세요'(请说)。" },
    { id:"kr16", ko:"다시 한 번 말해 주시겠어요?", zh:"您能再说一遍吗？", pron:"dasi han beon malhae jusigesseoyo", grammar:"正式请求重复。'다시'(再) + '한 번'(一次) + '말해 주시겠어요'(能说吗)。" },
    { id:"kr17", ko:"한국어를 공부하고 있어요.", zh:"我在学韩语。", pron:"hangugeoreul gongbuhago isseoyo", grammar:"自我介绍常用。'한국어'(韩语) + '를'(宾语助词) + '공부하다'(学习) + '고 있어요'(正在进行)。" },
    { id:"kr18", ko:"저는 중국에서 왔어요.", zh:"我来自中国。", pron:"jeoneun jungugeseo wasseoyo", grammar:"自我介绍。'저는'(我是, 主语) + '중국에서'(从中国) + '왔어요'(来了)。'에서' 表示来源地点。" },
    { id:"kr19", ko:"제 이름은 ___예요.", zh:"我的名字是___。", pron:"je ireumeun ___ yeyo", grammar:"自我介绍。'제'(我的, 谦语) + '이름은'(名字) + '___예요'(是___)。" },
    { id:"kr20", ko:"반갑습니다!", zh:"很高兴认识您！", pron:"bangapseumnida", grammar:"正式初次见面。'반갑다'(高兴) + '습니다'(敬语)。比 '반가워요' 更正式。" },

    // === 21-40 数字/时间 ===
    { id:"kr21", ko:"오늘은 며칠이에요?", zh:"今天几号？", pron:"oneureun myeochilieyo", grammar:"问日期。'오늘은'(今天是) + '며칠'(几号) + '이에요'(是)。'일'(天/号)。" },
    { id:"kr22", ko:"지금 몇 시예요?", zh:"现在几点？", pron:"jigeum myeot siyeyo", grammar:"问时间。'지금'(现在) + '몇 시'(几点) + '예요'(是)。'시'(点)。" },
    { id:"kr23", ko:"내일 만나요.", zh:"明天见。", pron:"naeil mannayo", grammar:"告别约定。'내일'(明天) + '만나요'(见吧)。'만나다'(见面)。" },
    { id:"kr24", ko:"주말에 뭐 할 거예요?", zh:"周末要做什么？", pron:"jumare mwol hal geoyeyo", grammar:"日常闲聊。'주말에'(在周末) + '뭐'(什么) + '할 거예요'(要做)。'-(으)ㄹ 거예요' 表未来计划。" },
    { id:"kr25", ko:"한 시간 후에 봐요.", zh:"一小时后见。", pron:"han sigan hue bwayo", grammar:"约定时间。'한 시간'(一小时) + '후에'(之后) + '봐요'(见)。'보다' 口语表「见面」。" },
    { id:"kr26", ko:"오늘 하루도 화이팅!", zh:"今天也加油！", pron:"oneul harudo hwaiting", grammar:"韩式鼓励语。'오늘 하루'(今天一天) + '도'(也) + '화이팅'(fighting 加油)。外来词，来自英语 fighting。" },
    { id:"kr27", ko:"아침 7시에 일어났어요.", zh:"我早上 7 点起床了。", pron:"achim 7sie ireonasseoyo", grammar:"叙述过去动作。'아침'(早上) + '일어나다'(起床) + '았어요'(过去式)。韩语过去式是 '았/었'。" },
    { id:"kr28", ko:"12시에 점심을 먹어요.", zh:"12 点吃午饭。", pron:"yeolduhsie jeomsimeul meogeoyo", grammar:"日常习惯。数字 12 读 '열두'(yeoldu)。「吃」是 '먹다'，'먹어요' 是现在时敬语。" },
    { id:"kr29", ko:"주말에 집에서 쉬고 싶어요.", zh:"周末想在家休息。", pron:"jumare jibeseo swigo sipeoyo", grammar:"表达愿望。'-(으)ㄹ 거예요' 表计划，'-(으)세요' 表请求，'고 싶어요' 表「想做」。" },
    { id:"kr30", ko:"지금 바빠요?", zh:"现在忙吗？", pron:"jigeum bappayo", grammar:"询问对方状态。'지금'(现在) + '바쁘다'(忙) + '아요'(现在时)。回答 '네, 바빠요'(是) 或 '아니요, 괜찮아요'(不，没关系)。" },
    { id:"kr31", ko:"3일 동안 여행 갔어요.", zh:"去旅行了 3 天。", pron:"samil dongan yeohaeng gasseoyo", grammar:"持续时间。'3일 동안'(3 天期间) + '여행'(旅行) + '갔어요'(去了)。'-(으)ㄹ 거예요' 表计划，过去式 '았/었'。" },
    { id:"kr32", ko:"매일 운동해요.", zh:"每天运动。", pron:"maeil undonghaeyo", grammar:"习惯频率。'매일'(每天) + '운동하다'(运动) + '아요'。'매일' 来自汉字 '每日'。" },
    { id:"kr33", ko:"주말에 보통 뭘 해요?", zh:"周末一般做什么？", pron:"jumare botong mwol haeyo", grammar:"询问习惯。'보통'(一般) + '뭘'(什么, 缩略) + '해요'(做)。'-(으)ㄴ/는' 表定语。" },
    { id:"kr34", ko:"오전에 회의가 있어요.", zh:"上午有会议。", pron:"ojeone hoeuiga isseoyo", grammar:"表达安排。'오전에'(在上午) + '회의'(会议) + '가'(主格) + '있어요'(有)。" },
    { id:"kr35", ko:"올해 30살이에요.", zh:"今年 30 岁。", pron:"olhae samsamsarieyo", grammar:"年龄表达。'올해'(今年) + '30살'(30 岁) + '이에요'(是)。韩语年龄是 '살'。" },
    { id:"kr36", ko:"생일이 언제예요?", zh:"生日是什么时候？", pron:"saengiri eonjeyeyo", grammar:"询问信息。'생일'(生日) + '이'(主格) + '언제'(什么时候) + '예요'(是)。" },
    { id:"kr37", ko:"7월 1일이에요.", zh:"是 7 月 1 日。", pron:"chilwol ilirieyo", grammar:"日期表达。月份读汉字音：7월=chilwol。日期纯韩语：1일=il, 2일=du, 3일=se, 4일=net..." },
    { id:"kr38", ko:"봄에는 벚꽃이 예뻐요.", zh:"春天樱花很美。", pron:"bomeeneun beotkkosi yeppeoyo", grammar:"季节描写。'봄에는'(在春天) + '벚꽃이'(樱花主格) + '예뻐요'(漂亮)。'-(으)ㄹ 거예요' 不对，要用现在时 '예쁘다 → 예뻐요'。" },
    { id:"kr39", ko:"여름에는 더워요.", zh:"夏天很热。", pron:"yeoreumeeneun deowoyo", grammar:"季节特点。'여름에는'(在夏天) + '덥다'(热) + '어요'。辅音 'ㅂ + ㅕ' 时 'ㅂ' 变 '워'。" },
    { id:"kr40", ko:"겨울에는 눈이 와요.", zh:"冬天下雪。", pron:"gyeoulleeneun nuni wayo", grammar:"自然现象。'겨울에는'(在冬天) + '눈이'(雪主格) + '와요'(下/来)。'오다'(来) 用作「下(雨雪)」。" },

    // === 41-60 食物/餐厅 ===
    { id:"kr41", ko:"배가 고파요.", zh:"我饿了。", pron:"baega gopayo", grammar:"身体状态。'배가'(肚子主格) + '고프다'(饿) + '아요'。'고프다' 的现在时是 '고파요'。" },
    { id:"kr42", ko:"목이 마르다.", zh:"口渴。", pron:"mogi mareuda", grammar:"身体感受。'목이'(嗓子主格) + '마르다'(渴)。这是陈述句，'마르다' 的词干后可直接接 '다'。" },
    { id:"kr43", ko:"매운 거 잘 먹어요.", zh:"我很能吃辣。", pron:"maeun geo jal meogeoyo", grammar:"能力/习惯。'매운 거'(辣的东西) + '잘'(善于) + '먹다'(吃) + '어요'。'-(으)ㄴ/는 거' 指代事物。" },
    { id:"kr44", ko:"이거 맛있어요.", zh:"这个好吃。", pron:"igeo masisseoyo", grammar:"评价食物。'이거'(这个) + '맛있다'(好吃) + '어요'。'맛있어요' 是敬语形式。" },
    { id:"kr45", ko:"김치찌개 주세요.", zh:"请给我一份泡菜汤。", pron:"gimchijjigae juseyo", grammar:"点餐。'주세요'(请给)。'주세요' = '주다'(给) + '세요'(请)。" },
    { id:"kr46", ko:"메뉴판 주시겠어요?", zh:"能给我菜单吗？", pron:"menyupan jusigesseoyo", grammar:"礼貌请求。'주시겠어요?'(能给我吗?) 是 '주세요' 的更礼貌形式。" },
    { id:"kr47", ko:"비빔밥 하나 주세요.", zh:"请给我一份拌饭。", pron:"bibimbap hana juseyo", grammar:"点餐。'비빔밥'(拌饭) + '하나'(一个, 辅音后) + '주세요'。数字 '하나/둘/셋...' 用于辅音后名词。" },
    { id:"kr48", ko:"계산해 주세요.", zh:"请结账。", pron:"gyesanhae juseyo", grammar:"餐厅用语。'계산하다'(结算) + '아/어 주세요'(请帮我)。'주세요' 是 '주다 + 세요'。" },
    { id:"kr49", ko:"맛있게 드세요.", zh:"请慢用。(用餐前)", pron:"masisge deuseyo", grammar:"韩国餐桌礼仪语。'맛있게'(美味地) + '드시다'(吃, 敬语) + '세요'。注意：动词 '먹다' 的敬语是 '드시다'。" },
    { id:"kr50", ko:"잘 먹었습니다.", zh:"我吃好了。(用餐后)", pron:"jal meogeosseumnida", grammar:"用餐后致谢。'잘 먹다'(好好吃) + '었습니다'(过去式敬语)。韩国礼仪：吃完要向做饭/请客的人说这句话。" },
    { id:"kr51", ko:"물 주세요.", zh:"请给我水。", pron:"mul juseyo", grammar:"点水。'물'(水) + '주세요'。'물' 是辅音开头，用 '을' 不用 '를'。" },
    { id:"kr52", ko:"커피 한 잔 마실래요?", zh:"要喝杯咖啡吗？", pron:"keopi han jan masillaeyo", grammar:"邀请。'한 잔'(一杯) + '마시다'(喝) + '-(으)ㄹ래요'(想/愿意)。'-(으)ㄹ래요' 表意愿。" },
    { id:"kr53", ko:"저는 커피보다 차를 더 좋아해요.", zh:"比起咖啡我更喜欢茶。", pron:"jeoneun keopiboda chareul deo joahaeyo", grammar:"比较。'A 보다 B'(比起A, B) + '더'(更) + '좋아하다'(喜欢)。" },
    { id:"kr54", ko:"매운 거 못 먹어요.", zh:"我不能吃辣。", pron:"maeun geo mot meogeoyo", grammar:"否定能力。'못'(不能) + '먹다'。'못' 否定能力，'안/아니' 否定意志或事实。" },
    { id:"kr55", ko:"한국 음식을 좋아해요.", zh:"我喜欢韩国料理。", pron:"hanguk eumsigeul joahaeyo", grammar:"表达喜好。'한국 음식'(韩国食物) + '을'(宾语) + '좋아하다'(喜欢) + '아요'。" },
    { id:"kr56", ko:"이 식당에 자주 와요?", zh:"你常来这家餐厅吗？", pron:"i sikdange jaju wayo", grammar:"询问频率。'자주'(经常) + '오다'(来) + '아요?'。回答 '네, 자주 와요'(是的，常来)。" },
    { id:"kr57", ko:"고기 굽는 거 좋아해요?", zh:"你喜欢烤肉吗？", pron:"gogi gupneun geo joahaeyo", grammar:"询问喜好。'굽다'(烤) + '-(으)ㄴ 거'(事情) + '좋아하다'(喜欢)。'-(으)ㄴ' 是定语形。" },
    { id:"kr58", ko:"맥주 한 병 주세요.", zh:"请给我一瓶啤酒。", pron:"maekju han byeong juseyo", grammar:"点啤酒。'맥주'(啤酒) + '한 병'(一瓶) + '주세요'。'병' 是瓶子量词。" },
    { id:"kr59", ko:"소주 한 잔 마셔도 돼요?", zh:"可以喝一杯烧酒吗？", pron:"soju han jan mashyeodo dwaeyo", grammar:"征求许可。'-(으)아/어도 돼요?'(可以做吗？)。'마시다'(喝) + '아/어도'(即使) + '되다'(可以)。" },
    { id:"kr60", ko:"한국의 김치가 정말 매워요.", zh:"韩国泡菜真的很辣。", pron:"hangugui gimchiga jeongmal maewoyo", grammar:"强调。'정말'(真的) + '맵다'(辣) + '어요'。'맵다' 变 '매워요'，辅音 'ㅂ' 遇 'ㅕ' 变 '워'。" },

    // === 61-80 情感表达 ===
    { id:"kr61", ko:"기분이 어때요?", zh:"心情怎么样？", pron:"gibuni eottaeyo", grammar:"询问状态。'기분'(心情) + '이'(主格) + '어떻다'(怎样) + '아요'。" },
    { id:"kr62", ko:"오늘 기분이 좋아요.", zh:"今天心情好。", pron:"oneul gibuni joayo", grammar:"描述状态。'오늘'(今天) + '기분이'(心情主格) + '좋다'(好) + '아요'。" },
    { id:"kr63", ko:"좀 피곤해요.", zh:"有点累。", pron:"jom pigeonhaeyo", grammar:"身体状态。'좀'(有点) + '피곤하다'(累) + '아요'。" },
    { id:"kr64", ko:"너무 행복해요!", zh:"太幸福了！", pron:"neomu haengbokaeyo", grammar:"强烈情感。'너무'(太) + '행복하다'(幸福) + '아요'。" },
    { id:"kr65", ko:"그렇게 말하면 슬퍼요.", zh:"你那样说让我难过。", pron:"geureoke malhamyeon seulpeoyo", grammar:"表达感受。'-(으)면'(如果/一...就) 引导条件。'그렇게'(那样) + '말하다'(说) + '면' + '슬프다'(伤心) + '어요'。" },
    { id:"kr66", ko:"보고 싶었어요.", zh:"我想你了。", pron:"bogo sippeosseoyo", grammar:"思念。'보다'(看) + '-(으)ㄹ 것 같다' 不对，要用 '-(으)ㅂ/습니다'。'보고 싶다'(想念) + '었어요'(过去式)。" },
    { id:"kr67", ko:"걱정하지 마세요.", zh:"请别担心。", pron:"geokjeonghaji maseyo", grammar:"安慰他人。'걱정하다'(担心) + '지 마세요'(请别)。'-(으)지 마세요' 表否定命令/请求。" },
    { id:"kr68", ko:"화 풀어요.", zh:"消消气。", pron:"hwa pureoyo", grammar:"安慰。'화'(气) + '풀다'(消) + '어요'。口语形式，正式可说 '화를 내지 마세요'(请别生气)。" },
    { id:"kr69", ko:"당신은 좋은 사람이에요.", zh:"你是好人。", pron:"dangsineun joen sarieyo", grammar:"称赞他人。'당신은'(你是) + '좋은'(好的, 定语) + '사람'(人) + '이에요'(是)。'-(으)ㄴ' 修饰名词。" },
    { id:"kr70", ko:"자랑스럽다.", zh:"(我为你) 感到骄傲。", pron:"jarangseureopda", grammar:"情感表达。'자랑스럽다'(感到骄傲) + '다'(陈述句尾)。可以说 '네가 자랑스럽다'(我为你骄傲)。" },
    { id:"kr71", ko:"고마워요. 정말요.", zh:"谢谢。真的(感谢)。", pron:"gomawo. jeongmaryo", grammar:"双重感谢。'정말로'(真的) 缩略 '정말요'。加重语气。" },
    { id:"kr72", ko:"미안해요. 제 잘못이에요.", zh:"对不起。是我的错。", pron:"mianhaeyo. je jalmotieyo", grammar:"道歉+认错。'미안하다'(对不起) + '제 잘못'(我的错) + '이에요'(是)。" },
    { id:"kr73", ko:"용서해 주세요.", zh:"请原谅我。", pron:"yongseohae juseyo", grammar:"请求原谅。'용서하다'(原谅) + '아/어 주세요'(请帮我)。" },
    { id:"kr74", ko:"오해였어요.", zh:"是误会。", pron:"ohaeyeosseoyo", grammar:"解释。'오해'(误会) + '이었다'(是, 过去式) + '어요'。" },
    { id:"kr75", ko:"다음에는 잘할게요.", zh:"下次我会做好的。", pron:"daeumeeneun jalhalkkeyo", grammar:"承诺。'다음에'(下次) + '잘하다'(做得好) + '-(으)ㄹ게요'(会/我会)。'-(으)ㄹ게요' 表承诺/意志。" },
    { id:"kr76", ko:"이해해요. 저도 그래요.", zh:"我理解。我也是。", pron:"ihaehaeyo. jeodo geuraeyo", grammar:"共情。'이해하다'(理解) + '아/어요'。'저도'(我也) + '그렇다'(那样) + '아요'。" },
    { id:"kr77", ko:"네 말이 맞아요.", zh:"你说得对。", pron:"ne mari majayo", grammar:"同意。'네 말'(你的话) + '이'(主格) + '맞다'(对) + '아요'。" },
    { id:"kr78", ko:"도움이 필요해요.", zh:"我需要帮助。", pron:"doumi piryohaeyo", grammar:"求助。'도움'(帮助) + '이'(主格) + '필요하다'(必要) + '아요'。" },
    { id:"kr79", ko:"힘들면 말해 주세요.", zh:"如果困难请告诉我。", pron:"himdeulmyeon malhae juseyo", grammar:"关心他人。'힘들다'(困难) + '-(으)면'(如果) + '말하다'(说) + '아/어 주세요'(请帮我)。" },
    { id:"kr80", ko:"다 잘될 거예요.", zh:"一切都会好起来的。", pron:"da jaldoel geoyeyo", grammar:"鼓励。'다'(都) + '잘되다'(顺利) + '-(으)ㄹ 거예요'(会)。" },

    // === 81-100 职场/学习 ===
    { id:"kr81", ko:"회의가 3시에 있어요.", zh:"会议 3 点开始。", pron:"hoeuiga sesie isseoyo", grammar:"日程表达。'회의'(会议) + '가'(主格) + '3시'(3 点) + '에'(在) + '있다'(有)。" },
    { id:"kr82", ko:"이메일 확인해 주세요.", zh:"请确认邮件。", pron:"imeil hwaginhae juseyo", grammar:"职场指令。'이메일'(邮件, 外来词) + '확인하다'(确认) + '아/어 주세요'。" },
    { id:"kr83", ko:"보고서 다 썼어요?", zh:"报告写完了吗？", pron:"bogoseo da sseosseoyo", grammar:"询问完成。'보고서'(报告) + '다'(都) + '쓰다'(写) + '었어요?'(过去式疑问)。" },
    { id:"kr84", ko:"내일까지 보내 주세요.", zh:"请在明天前发给我。", pron:"naeilkkaji bonae juseyo", grammar:"截止期限。'내일까지'(到明天为止) + '보내다'(发) + '아/어 주세요'。'-(으)까지' 表「到...为止」。" },
    { id:"kr85", ko:"잠깐만요.", zh:"请稍等。", pron:"jamkkanmanyo", grammar:"打断/等待。'잠깐'(一会儿) + '만'(只) + '요'(语气词)。" },
    { id:"kr86", ko:"회의실이 어디예요?", zh:"会议室在哪里？", pron:"hoeuisiri eodiyeyo", grammar:"询问地点。'회의실'(会议室) + '이'(主格) + '어디'(哪里) + '예요'(是)。" },
    { id:"kr87", ko:"지금 통화 가능해요?", zh:"现在能通话吗？", pron:"jigeum tonghwa ganeungaeyo", grammar:"确认时间。'통화'(通话) + '가능하다'(可能) + '아요?'。" },
    { id:"kr88", ko:"제안해 주셔서 감사합니다.", zh:"谢谢您的建议。", pron:"jeanhae jusyeoseo kamsahamnida", grammar:"商务致谢。'제안하다'(提议) + '아/어 주시다'(帮我的敬语) + '어서'(因为) + '감사합니다'。'-(으)아/어 주셔서' 表「因为帮我...」。" },
    { id:"kr89", ko:"좋은 의견이에요.", zh:"是个好意见。", pron:"joeun uigyeonieyo", grammar:"职场肯定。'좋은'(好的) + '의견'(意见) + '이에요'(是)。" },
    { id:"kr90", ko:"다시 생각해 볼게요.", zh:"我再想想看。", pron:"dasi saenggakae bolkkeyo", grammar:"委婉表达。'다시'(再) + '생각하다'(想) + '아/어 보다'(试试) + '-(으)ㄹ게요'(会)。" },
    { id:"kr91", ko:"그건 좀 어려워요.", zh:"那个有点难。", pron:"geugeon jom eoryeowoyo", grammar:"委婉拒绝。'그건'(那个) + '좀'(有点) + '어렵다'(难) + '어요'。" },
    { id:"kr92", ko:"연락 주세요.", zh:"请联系我。", pron:"yeollak juseyo", grammar:"商务常用。'연락'(联系) + '주다'(给) + '세요'。" },
    { id:"kr93", ko:"실례합니다.", zh:"打扰了。", pron:"sillyehamnida", grammar:"礼貌开场。'실례'(失礼) + '하다' + 'ㅂ니다'。进门/打断前说。" },
    { id:"kr94", ko:"감사합니다. 도움이 많이 됐어요.", zh:"谢谢。帮了大忙。", pron:"kamsahamnida. doumi mani dwaesseoyo", grammar:"致谢+说明。'도움이 되다'(有帮助)。'많이'(很多) + '됐어요'(成了)。" },
    { id:"kr95", ko:"한국어를 배운 지 1년이 됐어요.", zh:"学韩语已经 1 年了。", pron:"hangugeoreul baeun ji 1nyoni dwaesseoyo", grammar:"持续时间。'배우다'(学) + '-(으)ㄴ 지'(自从) + '1년'(1 年) + '되다'(成) + '었어요'。" },
    { id:"kr96", ko:"매일 한국 드라마를 봐요.", zh:"我每天看韩剧。", pron:"maeil hanguk deuramareul bwayo", grammar:"习惯。'매일'(每天) + '한국 드라마'(韩国电视剧) + '를'(宾语) + '보다'(看) + '아요'。" },
    { id:"kr97", ko:"한국 노래를 부르는 게 좋아요.", zh:"我喜欢唱韩语歌。", pron:"hanguk noraereul bureuneun ge joayo", grammar:"爱好。'-(으)ㄴ/는 게' 指代事情/行为。'부르다'(唱) + '는 것 + 좋다'。" },
    { id:"kr98", ko:"공부하느라 바빠요.", zh:"因为学习所以很忙。", pron:"gongbuhaneura bappayo", grammar:"原因。'공부하다'(学习) + '-(으)느라(고)' 表原因。'바쁘다'(忙)。" },
    { id:"kr99", ko:"한글은 어렵지 않아요.", zh:"韩文并不难。", pron:"hangeureun eoryeopji anayo", grammar:"否定。'어렵다'(难) + '-(으)지 않다'(不)。'어렵지 않아요' = 「不难」。" },
    { id:"kr100", ko:"노력하면 잘할 수 있어요.", zh:"努力的话就能做好。", pron:"noryeokhamyeon jalhalsu isseoyo", grammar:"条件+可能。'노력하다'(努力) + '-(으)면'(如果) + '잘하다'(做得好) + '-(으)ㄹ 수 있다'(能)。" },

    // === 101-120 旅行/购物 ===
    { id:"kr101", ko:"화장실이 어디예요?", zh:"洗手间在哪里？", pron:"hwajangsiri eodiyeyo", grammar:"询问地点。最高频旅行用语。'화장실'(洗手间) + '이'(主格) + '어디'(哪里) + '예요'(是)。" },
    { id:"kr102", ko:"지도를 보고 있어요.", zh:"我在看地图。", pron:"jidoleul bogo isseoyo", grammar:"正在做。'보다'(看) + '고 있다'(正在)。'지도를'(地图宾格) + '보다'。" },
    { id:"kr103", ko:"여기 사진 찍어도 돼요?", zh:"这里可以拍照吗？", pron:"yeogi sajin jjigeodo dwaeyo", grammar:"征求许可。'찍다'(拍) + '-(으)아/어도 되다'(可以)。" },
    { id:"kr104", ko:"이거 얼마예요?", zh:"这个多少钱？", pron:"igeo eolmayeyo", grammar:"购物问价。'이거'(这个) + '얼마'(多少) + '예요'(是)。回答 '천원이에요'(一千韩元)。" },
    { id:"kr105", ko:"너무 비싸요.", zh:"太贵了。", pron:"neomu bissayo", grammar:"议价。'너무'(太) + '비싸다'(贵) + '아요'。'비싸요' 辅音 'ㅆ' 后接 'ㅏ' 不变。" },
    { id:"kr106", ko:"깎아 주세요.", zh:"请便宜点。", pron:"kkakka juseyo", grammar:"议价。'깎다'(削价) + '아/어 주세요'。" },
    { id:"kr107", ko:"카드로 결제할게요.", zh:"我用卡支付。", pron:"kadeuro gyeoljehalgeyo", grammar:"付款方式。'카드'(卡, 外来词) + '로'(用) + '결제하다'(结算) + '-(으)ㄹ게요'。" },
    { id:"kr108", ko:"교환할 수 있어요?", zh:"可以换吗？", pron:"gyohwahal su isseoyo", grammar:"购物退换。'교환하다'(换) + '-(으)ㄹ 수 있다'(能)。" },
    { id:"kr109", ko:"택시 부르세요.", zh:"请叫出租车。", pron:"taeksi bureuseyo", grammar:"打车。'택시'(出租车) + '부르다'(叫) + '세요'。" },
    { id:"kr110", ko:"여기서 내려요.", zh:"我在这里下车。", pron:"yeogseo naeryeoyo", grammar:"打车用语。'내리다'(下) + '아요'。" },
    { id:"kr111", ko:"공항까지 가 주세요.", zh:"请送我去机场。", pron:"gonghangkkaji ga juseyo", grammar:"打车说明目的地。'-(으)까지'(到) + '가다'(去) + '아/어 주세요'。" },
    { id:"kr112", ko:"호텔은 예약했어요.", zh:"酒店已经预约了。", pron:"hotereun yeyakaesseoyo", grammar:"旅行预定。'예약하다'(预约) + '았어요'(过去式)。'호텔'(酒店, 外来词)。" },
    { id:"kr113", ko:"체크인 하고 싶어요.", zh:"我想办入住。", pron:"chekein hago sipeoyo", grammar:"酒店用语。'체크인'(check-in) + '하다' + '고 싶다'(想做)。'체크인' 是外来词。" },
    { id:"kr114", ko:"짐을 맡아 주세요.", zh:"请帮我寄存行李。", pron:"jimeul matja juseyo", grammar:"寄存行李。'맡다'(寄存) + '아/어 주세요'。" },
    { id:"kr115", ko:"가장 가까운 역은 어디예요?", zh:"最近的地铁站在哪？", pron:"gajang gakkaun yeogeun eodiyeyo", grammar:"问路。'가장'(最) + '가깝다'(近) + '은' 定语。'역'(站) + '은' + '어디'。" },
    { id:"kr116", ko:"왼쪽으로 가세요.", zh:"请往左走。", pron:"oenjjogeuro gaseyo", grammar:"指路。'왼쪽'(左) + '으로'(往) + '가다'(去) + '세요'。" },
    { id:"kr117", ko:"건너편에 있어요.", zh:"在对面。", pron:"geonneopyeone isseoyo", grammar:"指路。'건너편'(对面) + '에'(在) + '있다'(有)。" },
    { id:"kr118", ko:"비행기가 몇 시에 출발해요?", zh:"飞机几点起飞？", pron:"bihaengiga myeot sie chulbalhaeyo", grammar:"时间问询。'출발하다'(出发) + '아/어요'。" },
    { id:"kr119", ko:"여권을 보여 주세요.", zh:"请出示护照。", pron:"yeogwoneul boyeo juseyo", grammar:"海关用语。'여권'(护照) + '을'(宾语) + '보여 주다'(给我看) + '세요'。" },
    { id:"kr120", ko:"좋은 여행 되세요!", zh:"祝您旅途愉快！", pron:"joeun yeohaeng doeseyo", grammar:"旅行祝福。'좋은'(好的) + '여행'(旅行) + '되세요'(成为)。" }
  ],

  // ===== 韩语语法讲解 =====
  koreanNotes: {
    "kr01": "敬语体系：韩语分尊敬阶（습니다/세요）、准敬阶（아요/어요）、平语（반말/해）。对陌生人、长辈、上司必须用尊敬阶。",
    "kr05": "送别与迎接区分：客人离开时说 '안녕히 가세요'；迎接到达的人说 '안녕히 오세요'。'가다'(去) vs '오다'(来) 不要混用。",
    "kr11": "韩语职场中 '수고하셨습니다'(辛苦了) 是最常用的礼貌语。同事下班走时、完成任务时、上司对你说话时都说。",
    "kr27": "过去式：动词词干 + 았/었/였。元音 'ㅏ/ㅗ' 后用 '았'，'ㅏ/ㅗ' 之外用 '었'，'하' 变 '했'。'일어나다 + 았어요 = 일어났어요'。",
    "kr29": "想/意愿 三种表达：1) -(으)ㄹ 거예요 表计划(我将做) 2) -(으)ㄹ래요 表意愿(我想做) 3) -고 싶어요 表想做(我想做, 较温和)",
    "kr40": "自然现象动词：'비가 와요'(下雨, 雨来) '눈이 와요'(下雪) '바람이 불어요'(刮风) '천둥이 쳐요'(打雷)。",
    "kr50": "韩餐礼仪：用餐前 '잘 먹겠습니다'(我要吃了, 谦逊语)；用餐后 '잘 먹었습니다'(我吃好了, 感谢)。对准备食物/请客的人说。",
    "kr54": "否定形式：'안/아니' 否定意志或事实(不、没)；'못' 否定能力(不能)。'안 먹어요'(我不吃) vs '못 먹어요'(我不能吃) 不同。",
    "kr65": "条件/假设：'-(으)면' 表「如果/一...就」。动词有 'ㅡ' 时用 '-(으)면'，'말하다'→'말하면'，'가다'→'가면'。",
    "kr70": "主语省略：韩语常省略主语。'자랑스럽다' 实际是「(我/我们) 感到骄傲」的省略表达。完整是 '네가 자랑스럽다'(你让我骄傲)。",
    "kr75": "三种口语未来时：1) -(으)ㄹ게요 表承诺(我将...) 2) -(으)ㄹ 거예요 表计划(我打算...) 3) -(으)ㄹ래요 表意愿(我想...)",
    "kr95": "自从/经历时间：'动词 + -(으)ㄴ 지 + 时间' 表「做...已经多久」。'살다 + ㄴ 지 + 3년 = 산 지 3년'(住了 3 年了)。",
    "kr98": "原因：1) '-(으)아/어서' 表前后因果 2) '-(으)니까' 表发现原因 3) '-(으)느라고' 表因...而(带负面结果, 如学习而忙)。",
    "kr99": "否定形容词/动词：'X + -(으)지 않다'。'어렵다 + 지 않다 = 어렵지 않다'(不难)。口语常说 '어렵지 않아요'。"
  },

  // ===== 英语每日10句 =====
  english: [
    { id:"en1",  en:"The journey of a thousand miles begins with a single step.", zh:"千里之行，始于足下。" },
    { id:"en2",  en:"Happiness is not something ready-made; it comes from your own actions.", zh:"幸福不是现成的东西，它来自你自己的行动。" },
    { id:"en3",  en:"Your life does not get better by chance; it gets better by change.", zh:"你的生活不会因为偶然变好，它只会因为改变变好。" },
    { id:"en4",  en:"The only way to do great work is to love what you do.", zh:"做出伟大工作的唯一方法，就是热爱你所做的事。" },
    { id:"en5",  en:"Success is not final, failure is not fatal: it is the courage to continue that counts.", zh:"成功不是终点，失败也不是末日：重要的是继续前行的勇气。" },
    { id:"en6",  en:"Do not wait for the perfect moment; take the moment and make it perfect.", zh:"不要等待完美的时刻，要抓住这一刻并让它变得完美。" },
    { id:"en7",  en:"The greatest glory in living lies not in never falling, but in rising every time we fall.", zh:"生命最大的荣耀不在于从不跌倒，而在于每次跌倒后都能站起来。" },
    { id:"en8",  en:"Believe you can and you are already halfway to wherever you wish to go.", zh:"相信你能做到，你就已经在通往任何想去之地的半路上。" },
    { id:"en9",  en:"Act as if what you do makes a difference, because it truly does.", zh:"行动吧，仿佛你所做的一切都有意义，因为它确实如此。" },
    { id:"en10", en:"We are what we repeatedly do; excellence, then, is not an act but a habit.", zh:"我们反复做的事，决定了我们是怎样的人；因此，卓越不是一种行为，而是一种习惯。" }
  ],

  // ===== 英语语法讲解 =====
  englishNotes: {
    "en1": "主谓宾结构。journey 是单数名词，谓语动词用 begins。a thousand miles 是距离修饰，a single step 是宾语。整句用一般现在时陈述普遍真理。",
    "en2": "分号连接两个并列句。ready-made 是复合形容词作后置定语修饰 something。comes from 是动词短语表来源。your own actions 中 own 起强调作用。",
    "en3": "两个分句结构完全对称，形成对偶修辞。get better 是系表结构表变化。by chance 和 by change 仅差一个字母，尾韵和对比效果强。",
    "en4": "主语 the only way 后接不定式 to do great work 作定语；系动词 is 后接不定式 to love 作表语；what you do 是宾语从句。only 强调唯一性。",
    "en5": "冒号后是强调句型 It is ... that ...，强调主语 the courage to continue。final 和 fatal 头韵，形成铿锵节奏。count 在这里是动词「重要」。",
    "en6": "祈使句+分号+并列祈使句。wait for / take / make 三个动词形成行动递进。the moment 前后重复出现，形成 antanaclasis（同词异义反复）修辞。",
    "en7": "主语 glory 后接 in living 介词短语作定语。lies not in A but in B 是经典「不是A而是B」结构。every time 引导时间状语从句，相当于 whenever。",
    "en8": "祈使句 + and + 陈述句的固定结构，相当于 if 条件句。wherever 引导名词性从句作 to 的宾语。halfway to 是介词短语。",
    "en9": "as if 引导方式状语从句，从句中 what you do 是主语从句，makes a difference 是谓语。because 引导原因状语从句，does 替代 makes a difference 避免重复。",
    "en10": "表语从句 what we repeatedly do 中 repeatedly 是副词修饰 do。分号后用 then 承接。not an act but a habit 是「不是...而是...」结构，excellence 是抽象名词作主语。"
  },

  // ===== 韩语日常单词/短语（10个高频独立词汇） =====
  koreanWords: [
    { id:"kww1", ko:"뭐 해요?", zh:"在干嘛？", pron:"mwo haeyo", grammar:"뭐(什么) + 하다(做) + 아요(现在时敬语)。日常询问对方正在做什么。" },
    { id:"kww2", ko:"안녕", zh:"你好（随意）", pron:"annyeong", grammar:"안녕하세요 的简写，用于朋友、晚辈或非常熟悉的人之间。" },
    { id:"kww3", ko:"얼마예요?", zh:"多少钱？", pron:"eolmayeyo", grammar:"얼마(多少) + 예요(是)。购物问价最高频短句。" },
    { id:"kww4", ko:"어디예요?", zh:"在哪里？", pron:"eodiyeyo", grammar:"어디(哪里) + 예요(是)。问地点、找人、找东西都可以用。" },
    { id:"kww5", ko:"맛있어요", zh:"好吃", pron:"masisseoyo", grammar:"맛있다(好吃) 的现在时敬语形式。任何场合赞美食物必备。" },
    { id:"kww6", ko:"화장실", zh:"洗手间", pron:"hwajangsil", grammar:"名词。旅行/餐厅最高频词汇，常加 어디예요 使用。" },
    { id:"kww7", ko:"카페", zh:"咖啡店", pron:"kape", grammar:"来自英语 cafe 的外来词，韩语中泛指咖啡馆。" },
    { id:"kww8", ko:"택시", zh:"出租车", pron:"taeksi", grammar:"来自英语 taxi 的外来词，打车时说 '택시 불러 주세요'(请叫出租车)。" },
    { id:"kww9", ko:"물", zh:"水", pron:"mul", grammar:"名词。点餐时说 '물 주세요'(请给我水)。" },
    { id:"kww10", ko:"커피", zh:"咖啡", pron:"keopi", grammar:"来自英语 coffee 的外来词，韩国咖啡文化极盛行。" }
  ],

  // ===== 英语日常单词/短语（10个高频独立词汇） =====
  englishWords: [
    { id:"enw1", en:"What are you up to?", zh:"在干嘛？/ 在忙什么？", grammar:"口语高频问句。up to 在此表示「正在做/忙于」。比 What are you doing 更随意自然。" },
    { id:"enw2", en:"How much is it?", zh:"多少钱？", grammar:"购物问价最常用句。it 指代商品，is 可弱读。" },
    { id:"enw3", en:"Where is it?", zh:"在哪里？", grammar:"where 问地点 + be 动词 + 主语。寻找物品/地点最常用。" },
    { id:"enw4", en:"My treat.", zh:"我请客。", grammar:"treat 作名词表示「款待」。邀请吃饭付账时的地道表达。" },
    { id:"enw5", en:"Take care.", zh:"保重。", grammar:"告别用语，表示「照顾好自己」。正式、随意场合都通用。" },
    { id:"enw6", en:"Catch you later.", zh:"回头见。", grammar:"口语表达，= see you later。catch 在此无实义，整体表「之后再聊」。" },
    { id:"enw7", en:"No worries.", zh:"没关系/不客气。", grammar:"澳洲起源，现已成为全球通用口语。可回应道歉，也可替代 You're welcome。" },
    { id:"enw8", en:"I got it.", zh:"我明白了/我懂了。", grammar:"get 在此表示「理解」。过去式 got 在美式口语中常用，英式可说 I've got it。" },
    { id:"enw9", en:"Sounds good.", zh:"听起来不错。", pron:"", grammar:"省略主语 it，完整为 That sounds good。用于赞同对方提议。" },
    { id:"enw10", en:"What a day!", zh:"这一天！/ 今天真够受的！", grammar:"感叹句结构 What + a/an + 名词！根据语气可表「累惨了」也可表「太棒了」。" }
  ],

  // ===== 读书 =====
  reading: {
    // 顶部每日大金句
    dailyQuote: {
      en: "",
      zh: "",
      author: ""
    },
    // 好书推荐（删除了 status 字段）
    books: [
      { id:"bk1",  emoji:"📕", title:"非暴力沟通",  author:"马歇尔·卢森堡",     desc:"以同情和共情为基础的沟通方式，用「观察→感受→需要→请求」四步法化解冲突。", quote:"\"也许我们并不认为自己的谈话方式是「暴力」的，但我们的语言确实常常引发自己和别人的痛苦。\"" },
      { id:"bk2",  emoji:"📗", title:"金字塔原理",  author:"芭芭拉·明托",       desc:"结论先行的结构化表达方法，让你的汇报、写作、演讲逻辑更清晰。", quote:"\"在任何事面前都可以归纳出一个中心论点，可由三至七个论据支持。\"" },
      { id:"bk3",  emoji:"📘", title:"沟通的艺术",  author:"罗纳德·阿德勒",     desc:"全面涵盖有效倾听、清晰表达、非语言交流，通过大量案例提升沟通能力。", quote:"\"谈话的艺术是听和被听的艺术。\"" },
      { id:"bk4",  emoji:"📙", title:"关键对话",    author:"科里·帕特森",       desc:"掌握在高风险、情绪化、观点差异大的对话中实现有效沟通的技巧。", quote:"\"人们不会因为你表达的内容感到不快，他们只会因为你表达的方式感到不快。\"" },
      { id:"bk5",  emoji:"📓", title:"好好说话",    author:"马东 / 奇葩说团队", desc:"从话术底层逻辑出发，剖析沟通、说服、谈判、演讲、辩论五大场景。", quote:"\"说话是一门综合艺术，会说和说好之间隔着无数次打磨。\"" },
      { id:"bk6",  emoji:"📔", title:"被讨厌的勇气",author:"岸见一郎 / 古贺史健", desc:"阿德勒心理学的对话体入门书，教你如何拥有被讨厌的勇气走向自由。", quote:"\"一切烦恼都来自人际关系。\"" },
      { id:"bk7",  emoji:"📕", title:"原子习惯",    author:"詹姆斯·克利尔",     desc:"用「1%法则」建立好习惯、戒掉坏习惯，每天微小改变带来巨大复利效应。", quote:"\"你不是你的目标，你是你的系统。\"" },
      { id:"bk8",  emoji:"📗", title:"深度工作",    author:"卡尔·纽波特",       desc:"在分心时代培养深度专注能力，用高质量工作创造不可替代的价值。", quote:"\"你越能深度工作，就越能创造价值。\"" },
      { id:"bk9",  emoji:"📘", title:"影响力",      author:"罗伯特·西奥迪尼",   desc:"6 大说服原理：互惠、承诺一致、社会认同、喜好、权威、稀缺。", quote:"\"人们不是被你说服的，是被他们自己说服的。\"" },
      { id:"bk10", emoji:"📙", title:"思考，快与慢",author:"丹尼尔·卡尼曼",     desc:"诺贝尔经济学奖得主揭示大脑两套系统：直觉快思考与理性慢思考。", quote:"\"我们对自己认为自己知道的东西太自信了。\"" },
      { id:"bk11", emoji:"📓", title:"活法",        author:"稻盛和夫",           desc:"日本经营之圣的人生哲学：作为人，何谓正确？用简单的道理过不简单的人生。", quote:"\"工作是最好的修行。\"" },
      { id:"bk12", emoji:"📔", title:"刻意练习",    author:"安德斯·埃里克森",   desc:"天赋不是天生的，任何技能都可以通过科学方法刻意练习来精进。", quote:"\"没有刻意练习，就没有专家。\"" }
    ],

    // 每日网络爆火热梗（5-10 条/日，含来源依据，可已阅）
    slang: [
      { id:"sg1",  phrase:"遥遥领先", source:"华为发布会（2023 年余承东多次使用形容 Mate 60 等技术领先）", meaning:"形容某事物明显领先同行，现多用于调侃或强调优势。" },
      { id:"sg2",  phrase:"挖呀挖", source:"2023 年 4 月抖音幼师@音乐老师花开富贵 教唱儿歌《花园种花》走红", meaning:"原是一首手指谣，因旋律洗脑、老师甜美而成为全民模仿热梗。" },
      { id:"sg3",  phrase:"科目三", source:"广西民间婚礼习俗舞蹈 + 抖音神曲《一笑江湖》结合，2023 年底席卷全网", meaning:"指一种魔性舞步，因门槛低、节奏强，成为社交平台和年会必备。" },
      { id:"sg4",  phrase:"多巴胺", source:"2023 年夏季穿搭博主用「多巴胺穿搭」形容高饱和鲜艳色彩搭配", meaning:"原指神经递质，现泛指能带来快乐和活力的人/事/色彩。" },
      { id:"sg5",  phrase:"显眼包", source:"饭圈用语，指在人群中格外突出、自带吸睛效果的人", meaning:"形容行为夸张、造型抢眼或特别爱出风头的人，中性偏调侃。" },
      { id:"sg6",  phrase:"泼天的富贵", source:"古装剧/网络小说台词，2023 年被网友用来形容突如其来的巨大财富或好运", meaning:"形容极大、突如其来的好运、流量或财富。" },
      { id:"sg7",  phrase:"特种兵旅游", source:"2023 年五一/端午假期，年轻人用极短时间打卡超多景点的旅行方式走红", meaning:"指强度高、节奏快、景点密集的极限短途旅行。" },
      { id:"sg8",  phrase:"命运的齿轮", source:"抖音文案模板「命运的齿轮开始转动」大量二创，常用于讲述人生转折", meaning:"形容某个看似微小的决定或事件，引发后续一连串重大改变。" },
      { id:"sg9",  phrase:"泰裤辣", source:"歌手王琳凯 2023 年演唱会发言「太酷啦」的空耳变体", meaning:"「太酷啦」的谐音，用于表达认可、赞叹或玩味式肯定。" },
      { id:"sg10", phrase:"哈基米", source:"日语「蜂蜜」音译，因抖音《赛马娘》二创 BGM 中猫咪视频爆火", meaning:"现多用来称呼可爱的小猫小狗等宠物，表达宠溺。" },
      { id:"sg11", phrase:"纯爱战士", source:"二次元/影视圈概念，指只接受、只追求纯粹爱情的人", meaning:"形容坚信并追求无杂质、无功利爱情的人，也用于自嘲。" },
      { id:"sg12", phrase:"CPU 我", source:"演员许娣采访口误「PUA 我」被听成「CPU 我」后成为网络笑梗", meaning:"「PUA 我」的谐音变体，指被精神控制、被洗脑、被情感操控。" },
      { id:"sg13", phrase:"精神状态良好", source:"打工人自嘲用语，实际多用于反讽「已疯」「快崩了」", meaning:"表面说状态好，实际暗指压力大、濒临崩溃、需要发疯解压。" },
      { id:"sg14", phrase:"Citywalk", source:"2023 年小红书发起「Citywalk」话题，倡导无目的城市漫步", meaning:"指在城市里随意散步、探索街道小巷，强调慢节奏和发现感。" },
      { id:"sg15", phrase:"尊嘟假嘟", source:"源自宠物博主模仿幼童说话的可爱谐音梗", meaning:"「真的假的」的谐音卖萌版，用于表示惊讶或求证。" },
      { id:"sg16", phrase:"脆皮大学生", source:"2023 年大学生在社交媒体分享自己各种奇葩受伤经历", meaning:"指身体脆弱、容易受伤或生病的大学生，自嘲体质差。" },
      { id:"sg17", phrase:"南方小土豆", source:"2023 年底哈尔滨冰雪旅游热，东北网友对南方游客的昵称", meaning:"形容个子娇小、穿浅色羽绒服、去东北玩雪的南方游客。" },
      { id:"sg18", phrase:"i 人 / e 人", source:"MBTI 人格测试流行后，I（内向）和 E（外向）被简化为社交标签", meaning:"i 人指内向社恐型，e 人指外向社牛型。" },
      { id:"sg19", phrase:"我勒个豆", source:"河南方言「我嘞个豆」被网络玩梗，表达震惊", meaning:"「我的天呐」的方言版，表示惊讶、无语或感叹。" },
      { id:"sg20", phrase:"显眼包", source:"饭圈/综艺弹幕用语，指人群中格外抢眼的人或行为", meaning:"形容很抢眼、很突出、容易成为焦点的人或事物。" },
      { id:"sg21", phrase:"挖草", source:"「我靠」的谐音变体，因发音更温和而广泛使用", meaning:"表达惊讶、感叹或吐槽的口头禅。" },
      { id:"sg22", phrase:"依托答辩", source:"「一坨大便」的谐音委婉说法，B 站/贴吧常用来吐槽质量差", meaning:"形容某件事物质量极差、令人失望。" },
      { id:"sg23", phrase:"精神股东", source:"网友自嘲用语，指没买股票却天天关注某家公司动态的人", meaning:"形容对某个品牌/主播/公司投入过多情感和关注的人。" },
      { id:"sg24", phrase:"电子榨菜", source:"网友形容吃饭时刷的短视频/综艺/电视剧像榨菜一样下饭", meaning:"指适合下饭时看的轻松娱乐内容。" },
      { id:"sg25", phrase:"早 C 晚 A", source:"原为护肤术语（早 Vitamin C、晚 Vitamin A），后演变成早咖啡晚酒精", meaning:"形容年轻人白天靠咖啡续命、晚上靠酒精放松的生活状态。" }
    ],

    // 每日理财学习（30条，含标题/摘要/要点/外链/来源，每日2-3条不轮播）
    financeLearn: [
      { id:"fn1", emoji:"💰", title:"复利的力量：为什么巴菲特90%的财富在50岁后获得", desc:"解析复利的数学原理与时间杠杆，说明为何「越早投资越好」，用具体数字展示每月定投1000元30年后的差异。", points:"核心要点：复利三要素：本金、收益率、时间。时间是普通人最大的杠杆，年化8%下每月1000元定投30年可累积约150万。", link:"https://zh.wikipedia.org/wiki/%E5%A4%8D%E5%88%A9", source:"维基百科" },
      { id:"fn2", emoji:"📊", title:"资产配置入门：不要把鸡蛋放在一个篮子里", desc:"讲解资产配置的核心逻辑——股债平衡、分散风险，介绍经典的60/40组合和生命周期配置法。", points:"核心要点：分散+再平衡。年轻人可偏股（70%股30%债），随年龄增长逐步增加债券比例降低风险。", link:"https://zh.wikipedia.org/wiki/%E8%B5%84%E4%BA%A7%E9%85%8D%E7%BD%AE", source:"维基百科" },
      { id:"fn3", emoji:"📈", title:"基金定投实战：微笑曲线与止盈策略", desc:"详解定投的原理、微笑曲线的形成，以及常见的止盈方法（目标收益率止盈、估值止盈、动态再平衡）。", points:"核心要点：定投能平摊成本、克服择时焦虑；微笑曲线说明下跌时坚持买入反而能降低成本。", link:"https://zh.wikipedia.org/wiki/%E5%9F%BA%E9%87%91%E5%AE%9A%E6%8A%95", source:"维基百科" },
      { id:"fn4", emoji:"🏦", title:"紧急备用金：先保命，再谈增值", desc:"为什么理财第一步不是买股票，而是存够3-6个月生活费的紧急备用金？应该放在哪里（货币基金/短债）？", points:"核心要点：备用金要「安全、流动、随时可取」，金额=月支出×3~6，优先放货币基金或活期理财。", link:"https://www.zhihu.com/question/263568333", source:"知乎" },
      { id:"fn5", emoji:"📉", title:"股票到底是什么？普通人怎么参与？", desc:"从公司所有权角度理解股票，介绍A股、港股、美股基本规则，以及普通投资者参与的常见方式。", points:"核心要点：买股票=买公司的一部分；不懂不投，可通过指数基金间接持有整个市场。", link:"https://zh.wikipedia.org/wiki/%E8%82%A1%E7%A5%A8", source:"维基百科" },
      { id:"fn6", emoji:"🎯", title:"ETF：最适合普通人的指数投资工具", desc:"解释ETF（交易型开放式指数基金）的运作原理，对比ETF与主动基金的费用、透明度和交易灵活性。", points:"核心要点：ETF费率低、透明、可像股票一样交易；宽基ETF（沪深300/标普500）是新手首选。", link:"https://zh.wikipedia.org/wiki/%E4%BA%A4%E6%98%93%E5%9E%8B%E5%BC%80%E6%94%BE%E5%BC%8F%E6%8C%87%E6%95%B0%E5%9F%BA%E9%87%91", source:"维基百科" },
      { id:"fn7", emoji:"📜", title:"债券：稳健型投资者的压舱石", desc:"介绍债券的基本概念、国债/企业债/可转债的区别，以及债券在组合中降低波动的作用。", points:"核心要点：债券是「借条」，收益来自利息+价差；国债最安全，企业债收益高但需关注信用风险。", link:"https://zh.wikipedia.org/wiki/%E5%80%BA%E5%88%B8", source:"维基百科" },
      { id:"fn8", emoji:"🛡️", title:"保险怎么买？先保人，再保钱", desc:"讲解保障型保险（重疾、医疗、意外、寿险）与理财型保险的区别，以及配置顺序和保额估算。", points:"核心要点：先配齐「百万医疗+重疾+意外+定期寿险」，再考虑年金/增额寿；保费一般不超过年收入10%。", link:"https://zh.wikipedia.org/wiki/%E4%BF%9D%E9%99%A9", source:"维基百科" },
      { id:"fn9", emoji:"🧓", title:"养老金第三支柱：个人养老金怎么选", desc:"解读中国个人养老金制度：谁能参加、能买哪些产品、税收优惠怎么算、适合什么人。", points:"核心要点：年收入较高者更能享受税优；产品选FOF/存款/保险/基金，根据风险偏好和退休时间决定。", link:"https://zh.wikipedia.org/wiki/%E5%85%BB%E8%80%81%E4%BF%9D%E9%99%A9", source:"维基百科" },
      { id:"fn10", emoji:"💳", title:"信用卡的正确打开方式：积分与免息期", desc:"如何利用信用卡的免息期、积分、权益优化现金流，同时避免最低还款和分期的坑。", points:"核心要点：全额还款=免费借钱；最低还款和分期实际年化利率可能高达15%以上，要警惕。", link:"https://zh.wikipedia.org/wiki/%E4%BF%A1%E7%94%A8%E5%8D%A1", source:"维基百科" },
      { id:"fn11", emoji:"🏠", title:"买房还是租房？一笔该算清的账", desc:"从资产配置、现金流、机会成本角度分析买房与租房的决策框架，避免情感化决策。", points:"核心要点：比较「首付+月供」与「租金+投资差额」的总成本；房价涨幅、利率、流动性都要纳入计算。", link:"https://www.zhihu.com/question/19842937", source:"知乎" },
      { id:"fn12", emoji:"📝", title:"记账：财务自由的第一步", desc:"为什么记账能改变消费习惯？介绍几款主流记账方法和「预算=给每一块钱分配任务」的理念。", points:"核心要点：记账不是为了省钱，而是为了看清钱去哪了；坚持30天就能发现至少一笔可优化支出。", link:"https://zh.wikipedia.org/wiki/%E4%B8%AA%E4%BA%BA%E7%90%86%E8%B4%A2", source:"维基百科" },
      { id:"fn13", emoji:"🚫", title:"远离消费贷：负债如何吃掉你的未来", desc:"分析消费贷、现金贷、分期购物的真实利率，以及高负债对现金流和心理的长期影响。", points:"核心要点：分期手续费换算成年化往往高得惊人；先还债再投资，高息负债优先还。", link:"https://zh.wikipedia.org/wiki/%E6%B6%88%E8%B4%B9%E8%80%85%E4%BF%A1%E8%B4%B7", source:"维基百科" },
      { id:"fn14", emoji:"🧮", title:"IRR 和年化收益率：别被数字骗了", desc:"讲解 IRR（内部收益率）、XIRR、七日年化、成立以来收益等概念的区别和使用场景。", points:"核心要点：不同产品要用同一口径比较，最常用的是年化收益率（IRR/XIRR），注意扣除费用。", link:"https://zh.wikipedia.org/wiki/%E5%86%85%E9%83%A8%E6%94%B6%E7%9B%8A%E7%8E%87", source:"维基百科" },
      { id:"fn15", emoji:"🌟", title:"FIRE运动：财务自由，提前退休", desc:"介绍FIRE（Financial Independence, Retire Early）的4%法则、 LeanFIRE 与 FatFIRE 的区别。", points:"核心要点：4%法则指每年提取本金的4%作为生活费；本金=年支出×25。降低物欲是关键。", link:"https://zh.wikipedia.org/wiki/FIRE%E9%81%8B%E5%8B%95", source:"维基百科" },
      { id:"fn16", emoji:"📑", title:"如何阅读基金招募说明书？", desc:"讲解基金招募书中的关键章节：投资目标、费率结构、业绩基准、风险收益特征、基金经理。", points:"核心要点：重点看「费率、持仓、业绩比较基准、最大回撤」；成立时间太短、规模太小的基金慎选。", link:"https://www.zhihu.com/question/21045254", source:"知乎" },
      { id:"fn17", emoji:"🪙", title:"黄金：避险资产还是投机工具？", desc:"分析黄金的属性、影响金价的因素，以及黄金在个人组合中的合理配置比例。", points:"核心要点：黄金不生息，主要作用是抗通胀和避险；配置比例一般5%-10%，不宜过重。", link:"https://zh.wikipedia.org/wiki/%E9%BB%84%E9%87%91", source:"维基百科" },
      { id:"fn18", emoji:"📰", title:"财报入门：三表到底在看什么？", desc:"通俗解读资产负债表、利润表、现金流量表，以及几个关键指标（ROE、毛利率、负债率）。", points:"核心要点：ROE看盈利能力，现金流看造血能力，负债率看抗风险能力；三表结合看，不可单看利润。", link:"https://zh.wikipedia.org/wiki/%E8%B4%A2%E5%8A%A1%E6%8A%A5%E8%A1%A8", source:"维基百科" },
      { id:"fn19", emoji:"🧠", title:"行为金融学：为什么你总是高买低卖", desc:"介绍损失厌恶、追涨杀跌、锚定效应、过度自信等常见投资心理陷阱。", points:"核心要点：投资最大的敌人往往是自己；制定规则并严格执行，比凭感觉操作更可靠。", link:"https://zh.wikipedia.org/wiki/%E8%A1%8C%E4%B8%BA%E9%87%91%E8%9E%8D%E5%AD%A6", source:"维基百科" },
      { id:"fn20", emoji:"🧾", title:"个税专项附加扣除：每年能省多少钱", desc:"解读子女教育、继续教育、大病医疗、住房贷款利息、住房租金、赡养老人等专项附加扣除。", points:"核心要点：每年12月确认下一年度专项扣除；房租和房贷利息只能二选一；合理填报可节税。", link:"https://zh.wikipedia.org/wiki/%E4%B8%AA%E4%BA%BA%E6%89%80%E5%BE%97%E7%A8%8E", source:"维基百科" },
      { id:"fn21", emoji:"🔒", title:"投资中最重要的两个字：安全边际", desc:"讲解安全边际理念（Margin of Safety），即只以远低于内在价值的价格买入，留足容错空间。", points:"核心要点：再好的公司，买贵了也危险；安全边际能保护你在判断错误时少亏钱。", link:"https://www.zhihu.com/question/20339854", source:"知乎" },
      { id:"fn22", emoji:"📅", title:"定投日选哪天？其实没那么重要", desc:"用历史数据回测说明周几定投、月定投、双周定投的收益差异其实很小，关键是坚持。", points:"核心要点：择时收益贡献远小于「开始早+坚持久+纪律再平衡」；与其纠结日期，不如现在就投。", link:"https://www.zhihu.com/question/266797958", source:"知乎" },
      { id:"fn23", emoji:"🌐", title:"全球配置：为什么也要看海外市场", desc:"介绍A股、港股、美股、新兴市场等市场的配置逻辑，以及汇率对海外投资的影响。", points:"核心要点：单一市场风险集中；通过QDII基金可便捷配置海外资产，比例视风险承受能力而定。", link:"https://zh.wikipedia.org/wiki/%E5%85%A8%E7%90%83%E6%8A%95%E8%B5%84", source:"维基百科" },
      { id:"fn24", emoji:"⚠️", title:"识别非法集资与金融诈骗", desc:"总结常见骗局特征：保本高收益、拉人头返利、期限错配、无金融牌照、资金去向不明。", points:"核心要点：收益超过6%就要打问号，超过8%很危险，超过10%就要做好损失全部本金的准备。", link:"https://zh.wikipedia.org/wiki/%E9%9D%9E%E6%B3%95%E9%9B%86%E8%B5%84", source:"维基百科" },
      { id:"fn25", emoji:"🔄", title:"再平衡：让组合不跑偏的关键动作", desc:"讲解什么是再平衡、为什么要做、多久做一次，以及阈值再平衡vs定期再平衡的优缺点。", points:"核心要点：再平衡能强制「低买高卖」；一般每年或偏离目标配置10%时做一次即可。", link:"https://www.zhihu.com/question/23916565", source:"知乎" },
      { id:"fn26", emoji:"🎁", title:"保险中的「现金价值」是什么？", desc:"解释现金价值的概念、计算方式，以及它在退保、保单贷款、减额交清时的作用。", points:"核心要点：现金价值=保单里能拿出来的钱；早期退保损失大，买长期险前要充分了解。", link:"https://zh.wikipedia.org/wiki/%E4%BA%BA%E5%AF%BF%E4%BF%9D%E9%99%A9", source:"维基百科" },
      { id:"fn27", emoji:"🛒", title:"智能投顾：AI 帮你做资产配置", desc:"介绍智能投顾的工作原理、优缺点、适合人群，以及与传统理财顾问的区别。", points:"核心要点：智能投顾门槛低、费率透明，适合没时间研究、追求纪律化配置的投资者。", link:"https://zh.wikipedia.org/wiki/%E6%99%BA%E8%83%BD%E6%8A%95%E9%A1%BE", source:"维基百科" },
      { id:"fn28", emoji:"🏆", title:"投资大师们的一致建议：长期持有", desc:"总结巴菲特、芒格、约翰·博格等投资大师关于长期主义、指数基金、控制成本的共同观点。", points:"核心要点：长期持有优质资产+控制成本+保持理性，是普通投资者胜率最高的路径。", link:"https://www.zhihu.com/question/22919860", source:"知乎" },
      { id:"fn29", emoji:"🧩", title:"家庭资产配置的四账户法", desc:"介绍标准普尔家庭资产象限图：要花的钱、保命的钱、生钱的钱、保本升值的钱。", points:"核心要点：10%短期消费、20%保障、30%高风险投资、40%稳健理财，比例可根据家庭阶段调整。", link:"https://www.zhihu.com/question/27903174", source:"知乎" },
      { id:"fn30", emoji:"🚀", title:"年轻人的第一桶金：从0到10万", desc:"拆解第一桶金的积累路径：提高收入、控制支出、建立储蓄率、选择合适工具、保持耐心。", points:"核心要点：第一桶金靠储蓄，之后靠投资；储蓄率提升到30%以上，复利才有明显效果。", link:"https://www.zhihu.com/question/23916565", source:"知乎" }
    ]
  },

  // ===== 情商成长 =====
  eqGrowth: [
    { id:"eq1",  emoji:"🤝", title:"先处理情绪，再处理事情",      content:"对方正在气头上时，所有「讲道理」都会失效。等对方情绪平复（物理降温：喝杯水、走走），再谈事情，效率会提升十倍。",                            practice:"今日练习：有人对你发火时，深呼吸 3 次，回应「我听到你生气了，我们冷静一下再聊」。" },
    { id:"eq2",  emoji:"👂", title:"认真听别人说完再开口",        content:"大多数人听别人说话时，脑子里已经在准备自己的回应。真正的倾听，是让对方完整表达完，再确认「你说的意思是...对吗？」",                  practice:"今日练习：在会议中让每个人说完再发言。别人没说完不打断，是职场最被低估的高情商表现。" },
    { id:"eq3",  emoji:"🎁", title:"回应永远比建议更有力",        content:"当别人向你倾诉时，他们要的不是解决方案，而是「我懂你」。回应「这确实挺难的」「换成我也会这么想」，比直接给建议更暖。",              practice:"今日练习：朋友吐槽时忍住「那你可以...」的冲动，先说「我懂，这种情况下真的会难受。」" },
    { id:"eq4",  emoji:"🙇", title:"会道歉的人最强大",            content:"主动道歉不是软弱，是把关系的主导权抢回来。「对不起，刚才我语气急了」一句话能化解八成冲突。",                                          practice:"今日练习：观察自己最近一次冲突，主动发条消息「上次我没控制好情绪，抱歉」。" },
    { id:"eq5",  emoji:"🌟", title:"让别人感觉被看见",            content:"记住对方说过的小事（孩子的名字、上周提的咖啡、上次会议里那句观点），下次见面提一句，对方会被打动。",                                  practice:"今日练习：找一位同事/朋友，发条消息「上次你说想看 XX，我记得哦」。" },
    { id:"eq6",  emoji:"🪞", title:"把「你总是」「你从不」换成「我感到」", content:"指责性语言（You always / You never）会让人立刻筑墙。换「我感到被忽视」/「我希望被提前告知」，对方更愿意倾听。",           practice:"今日练习：下次想抱怨时，先在脑内把「你总是不接电话」转成「我打电话没接通时会担心」。" },
    { id:"eq7",  emoji:"🧭", title:"拒绝时要温柔，答应时要坚定",  content:"「温柔的拒绝」：我超想做，但今天实在排不开，下周可以吗？温柔的拒绝比冷冰冰的「没空」更让人舒服。",                                practice:"今日练习：把今天的 3 个「没办法」换成「我超想做，但是...(给出具体替代方案）。" },
    { id:"eq8",  emoji:"🪄", title:"夸奖要具体，越具体越真诚",    content:"「你真棒」走心指数 3 分，「你刚才那段汇报里那个比喻特别形象」走心指数 9 分。",                                                       practice:"今日练习：向一位同事发出具体表扬：「你说的那句『客户的沉默才是最贵的成本』特别戳中我」。" },
    { id:"eq9",  emoji:"🧊", title:"冷处理不是冷暴力",            content:"情绪上头时说「我需要 10 分钟想想」是成熟的表现，但一定要补一句「我不是不理你，是怕说错话」。冷处理的关键是给对方一个预期。",        practice:"今日练习：下次想摔门时，改成说「我出去走走，15 分钟后回来聊」。" },
    { id:"eq10", emoji:"🪟", title:"批评 Sandwich 法：好-坏-好",  content:"先肯定一个优点，再指出问题，最后给一个可操作的改进建议。让对方觉得你是站在他这边的，而不是在挑刺。",                          practice:"今日练习：用三明治法给一位同事提建议：肯定+问题+建议，观察对方反应。" },
    { id:"eq11", emoji:"🎭", title:"察言观色：读懂没说出口的话",    content:"对方突然沉默、看手机、回答变短——这些都是「不感兴趣」或「不赞同」的信号。高情商的人不会追问，而是自然转换话题或给对方台阶。",        practice:"今日练习：聊天时观察对方的肢体语言，如果对方双臂交叉或后仰，主动换话题。" },
    { id:"eq12", emoji:"⚖️", title:"公平不等于一样对待每个人",    content:"对内向的人多给思考时间，对外向的人多给表达空间。真正的公平是根据每个人的需求调整你的沟通方式，而不是一刀切。",                  practice:"今日练习：今天跟不同性格的人沟通时，刻意调整你的语速和方式。" },
    { id:"eq13", emoji:"🌱", title:"允许别人犯错，比帮别人纠错更难", content:"看到别人走弯路时，忍住「我早告诉过你」的冲动。让对方自己撞墙、自己总结，是最好的成长方式。你只需要在对方求助时出现。",            practice:"今日练习：忍住一次「插手帮忙」的冲动，改为问「需要我帮忙吗？」" },
    { id:"eq14", emoji:"🫖", title:"茶水间社交：5 分钟比 1 小时会议更有效", content:"真正的关系不是在会议室里建立的，而是在茶水间、电梯里、午餐时。每天花 5 分钟跟不熟悉的同事闲聊，长期回报远超你的想象。",   practice:"今日练习：今天主动找一个不太熟的同事聊 3 分钟非工作话题。" },
    { id:"eq15", emoji:"🧲", title:"求助是最被低估的社交技能",    content:"「你能帮我看看这个吗？」比「我很厉害」更能拉近关系。本杰明·富兰克林效应：帮过你的人，更愿意再帮你。求助不是示弱，是给对方价值感。", practice:"今日练习：找一个比你擅长某事的人，真诚请教一个具体问题。" },
    { id:"eq16", emoji:"🌙", title:"睡前复盘：今天哪句话可以说得更好", content:"每天花 2 分钟回想今天最有情绪波动的一次对话，问自己「如果重来一次，我会怎么说？」这个习惯坚持一个月，你的沟通能力会发生质变。", practice:"今日练习：今晚睡前回忆今天一次对话，写下更好的表达方式。" },
    { id:"eq17", emoji:"🌉", title:"把「但是」换成「同时」",         content:"「你想法很好，但是……」让人只听到后半句的否定。换成「你想法很好，同时我需要考虑预算」，更容易被接受。", practice:"今日练习：把一次反馈中的「但是」替换成「同时」。" },
    { id:"eq18", emoji:"🎣", title:"用问题代替说教",               content:"直接给答案会让人防御，提问会让对方自己找到答案。把「你应该……」换成「你怎么看……」。", practice:"今日练习：遇到同事求助时，先问「你尝试过什么？」而不是直接给方案。" },
    { id:"eq19", emoji:"🧯", title:"情绪上头时先给情绪命名",       content:"「我现在很愤怒」比单纯发火更能降低情绪强度。心理学上这叫「情绪标签化」，是快速冷静的有效方法。", practice:"今日练习：情绪强烈时，在心里说出「我现在感到___」。" },
    { id:"eq20", emoji:"🪞", title:"别急着做「好人」",             content:"为了不被讨厌而答应所有请求，最终只会委屈自己。真正的善良是有边界的，拒绝不合理要求是对关系负责。", practice:"今日练习：拒绝一件你不想做、也没义务做的事。" },
    { id:"eq21", emoji:"🌤️", title:"开场白决定沟通温度",           content:"无论是发消息还是见面，先说一句轻松的开场（天气、共同经历、关心），比直奔主题让人更愿意配合。", practice:"今日练习：给同事/朋友发消息时，先加一句非事务性的问候。" },
    { id:"eq22", emoji:"🧭", title:"分清事实和观点",               content:"「你总是迟到」是观点，「你这周三次会议都迟到了 5 分钟」是事实。用事实沟通，冲突少一半。", practice:"今日练习：准备提出批评时，先列出 3 个具体事实。" },
    { id:"eq23", emoji:"🫂", title:"别人自嘲时别跟着踩",           content:"对方说「我太胖了」，你回答「是有点」会伤人；回答「哪有，我觉得你状态很好」才暖心。自嘲是求安慰，不是求认同。", practice:"今日练习：朋友自嘲时，给一句肯定而不是附和。" },
    { id:"eq24", emoji:"🧩", title:"关系维护靠「小事」",           content:"生日祝福、记得过敏食物、顺手带杯咖啡——这些小事比大事更能维系关系。人们记住的往往不是大事，是被放在心上的感觉。", practice:"今日练习：为身边某个人做一件不刻意但贴心的小事。" },
    { id:"eq25", emoji:"🎭", title:"不懂就别装懂",                 content:"承认「这个我不太了解」不仅不会丢人，反而让人觉得你诚实可信。不懂装懂被拆穿时，损失的是长期信任。", practice:"今日练习：遇到不懂的话题，大方说「这个我得查查/了解一下」。" },
    { id:"eq26", emoji:"🌿", title:"给对方留台阶",                 content:"即使你有理，也不要把对方逼到墙角。说「可能是我们理解角度不同」比「你错了」更容易达成共识。", practice:"今日练习：争论时，尝试用「我理解你的角度」开场。" },
    { id:"eq27", emoji:"🧮", title:"情绪账本的智慧",               content:"每一次耐心倾听、真诚赞美都是在存情感余额；每一次嘲讽、敷衍都是在透支。高情商的人懂得长期记账。", practice:"今日练习：回想你和某人的「情绪账本」，你今天能存一笔吗？" },
    { id:"eq28", emoji:"🔮", title:"预期管理是最好的情商",         content:"做不到的事情提前说明，比最后失约好一万倍。「我尽量周五前给你，但不排除要周一」比「好的」更让人安心。", practice:"今日练习：答应一件事时，同时说明可能的风险和时间。" },
    { id:"eq29", emoji:"🎯", title:"赞美对方的努力，而非天赋",     content:"「你练了很久吧」比「你真有天赋」更能激励人。夸努力会让人相信成长，夸天赋会让人害怕失败。", practice:"今日练习：夸奖时具体提到对方付出的努力或坚持。" },
    { id:"eq30", emoji:"🧘", title:"沉默也是沟通的一部分",         content:"不必急于填补所有安静。适当的沉默给对方思考空间，也让你显得更有底气。最怕的是因为怕尴尬而乱说话。", practice:"今日练习：聊天中刻意停顿 2 秒再回应，观察效果。" }
  ],

  // ===== 办公技巧 =====
  officeTips: [
    { id:"ot1",  emoji:"⌨️", category:"快捷键",   title:"Windows / Mac 通用高频快捷键", content:"复制 Ctrl/⌘+C，粘贴 Ctrl/⌘+V，撤销 Ctrl/⌘+Z，查找 Ctrl/⌘+F，全选 Ctrl/⌘+A，切换程序 Alt/⌘+Tab，关闭程序 Alt/⌘+F4 / ⌘+Q，新建窗口 Ctrl/⌘+N。" },
    { id:"ot2",  emoji:"✂️", category:"效率神器", title:"剪贴板历史：Win+V",                content:"Win+V 打开剪贴板历史（需开启），可以同时粘贴多条之前复制的内容。再也不用反复来回切窗口复制粘贴。" },
    { id:"ot3",  emoji:"🔍", category:"效率神器", title:"桌面秒搜：Everything（仅 Windows）",content:"安装 Everything（免费），按下 Alt+Space 唤起，输入任意文件名 0.1 秒内找到本地任何文件。比资源管理器快 100 倍。" },
    { id:"ot4",  emoji:"🖼️", category:"截图录屏", title:"Windows Shift+S，Mac Shift+⌘+4", content:"Windows 按 Shift+Win+S 弹出截图工具（矩形/窗口/全屏），Mac 按 ⌘+Shift+4 部分截图、+空格全屏窗口截图。截图自动进剪贴板。" },
    { id:"ot5",  emoji:"📧", category:"邮件技巧", title:"邮件标题必带动作词 + 关键时间点",  content:"好标题：【请审批】《Q3 营销方案》v2（截止 8/5）。差标题：方案。动作词 + 文档名 + 版本 + 节点，一眼就知道该做什么。" },
    { id:"ot6",  emoji:"📊", category:"Excel 技巧",title:"Ctrl+E 快速填充（Excel 2016+）",   content:"在第一行手动写一个示例（如把姓名拆成姓 / 名两列），按 Ctrl+E 一秒自动填充剩下所有行。是 Excel 最被低估的神器。" },
    { id:"ot7",  emoji:"📊", category:"Excel 技巧",title:"VLOOKUP → XLOOKUP（Excel 365）",   content:"新公式 =XLOOKUP(查找值, 查找区域, 返回区域)。比 VLOOKUP 简单 10 倍：不用数列数、不用 FALSE、近似匹配自动处理。" },
    { id:"ot8",  emoji:"📑", category:"PPT 技巧", title:"Alt+F10 对齐参考线",                content:"选中多个元素按 Alt+F10 召唤对齐参考线，PPT 自动给红绿蓝三色辅助线对齐到中心 / 边缘。秒杀手工拖动对不齐的烦恼。" },
    { id:"ot9",  emoji:"🎨", category:"PPT 技巧", title:"一键替换字体 + 一键更换主题色",    content:"设计 → 变体 → 颜色（主题色）：鼠标点击可全文档一次性换主题色。换字体：选中母版编辑一次，全部页面生效。",                practice:"今日练习：把所有幻灯片的标题统一为思源黑体粗体，3 分钟搞定。" },
    { id:"ot10", emoji:"📱", category:"时间管理", title:"番茄工作法变种：52+17",            content:"严格 25+5 太累。新版番茄：专注 52 分钟，休息 17 分钟（黄金比例），每 4 个番茄做一次长休息。Google、阿里内部都推行过。" },
    { id:"ot11", emoji:"📅", category:"会议技巧", title:"站立会议不是敏捷专属，3 分钟也能开",content:"站着开会比坐着开效率高 30%（剑桥大学研究）。站着人不会久坐偷看手机，自然简短直接。10 人以下会议默认站立。" },
    { id:"ot12", emoji:"🧮", category:"文档技巧", title:"Word 标题样式 = 自动目录",          content:"别手动敲标题样式。写文档时坚持给每章应用「标题 1」「标题 2」样式，最后「引用 → 目录」一键生成完美目录，还能一键跳转。" },
    { id:"ot13", emoji:"⌨️", category:"快捷键",   title:"Win+D 秒回桌面，再按一次恢复",      content:"开会前老板突然走过来？Win+D 一键最小化所有窗口显示桌面，再按一次 Win+D 恢复所有窗口。比 Alt+Tab 更干净利落。" },
    { id:"ot14", emoji:"📧", category:"邮件技巧", title:"收件人最后填，附件先检查",          content:"写邮件时先写正文、加附件，最后再填收件人。避免写到一半误点发送。养成习惯后永远不会出现「忘记附件」的尴尬。" },
    { id:"ot15", emoji:"📊", category:"Excel 技巧",title:"Alt+= 一键求和",                    content:"选中数据区域下方或右侧的空单元格，按 Alt+=（Mac 是 Shift+⌘+T），Excel 自动判断范围并填入 SUM 公式。比手动输入快 10 倍。" },
    { id:"ot16", emoji:"🎨", category:"PPT 技巧", title:"Ctrl+Shift+C / V 复制格式",        content:"选中一个漂亮的文本框，Ctrl+Shift+C 复制格式，再选中目标文本框 Ctrl+Shift+V 粘贴格式。比格式刷还好用，可以跨幻灯片使用。" },
    { id:"ot17", emoji:"⏰", category:"时间管理", title:"2 分钟法则：能 2 分钟做完的事立刻做",content:"如果一件事 2 分钟内能完成，不要加到待办清单，立刻做掉。这是 GTD（Getting Things Done）的核心原则之一，能大幅减少待办堆积。" },
    { id:"ot18", emoji:"📝", category:"会议技巧", title:"会后 5 分钟发纪要：谁、做什么、什么时候",content:"开会最怕开了等于没开。会后 5 分钟内发一条简短纪要：1）决定了什么 2）谁负责 3）什么时候交。养成习惯，你的执行力会甩开 80% 的人。" },
    { id:"ot19", emoji:"🔍", category:"效率神器", title:"浏览器 Ctrl+Shift+T 恢复关闭的标签页",content:"不小心关了重要网页？Ctrl+Shift+T（Mac 是 ⌘+Shift+T）恢复最近关闭的标签页，可以连续按多次恢复多个。比翻历史记录快太多了。" },
    { id:"ot20", emoji:"📋", category:"文档技巧", title:"F4 重复上一步操作",                  content:"在 Office 里按 F4 会重复你上一步操作。比如你刚把一段文字标红，选中另一段按 F4 它也变红。PPT 里对齐、Excel 里填色都适用，效率翻倍。" },
    { id:"ot21", emoji:"📅", category:"会议技巧", title:"开会前 30 秒发议程",                content:"会议开始前在群里/邮件里发一句「今天讨论 3 件事：A、B、C，预计 20 分钟」。参会者会立刻进入状态，会议效率提升 50%。" },
    { id:"ot22", emoji:"🧮", category:"Excel 技巧", title:"Ctrl+T 把区域变成超级表",          content:"选中数据按 Ctrl+T 创建 Excel 表，自动筛选、自动扩展公式、自动美化。新增行时公式和格式会自动继承。" },
    { id:"ot23", emoji:"🎨", category:"PPT 技巧", title:"SmartArt 一键把文字变图表",        content:"选中文字 → 右键 → 转换为 SmartArt。枯燥的 bullet point 瞬间变成流程图/循环图/层级图，演示专业度立刻提升。" },
    { id:"ot24", emoji:"📧", category:"邮件技巧", title:"邮件正文用「结论先行 + 3 点支撑」", content:"第一段写结论，下面用 1/2/3 列证据/行动项。老板和合作方没时间读完长篇大论，先给答案再补充细节。" },
    { id:"ot25", emoji:"⏰", category:"时间管理", title:"日历预约自己的工作块",              content:"把重要但不紧急的事（学习、写方案、深度工作）直接预约进日历。别人会尊重你日历上的「忙碌」，你也能保护自己的专注时间。" },
    { id:"ot26", emoji:"📝", category:"文档技巧", title:"写文档先列大纲再填内容",            content:"不要打开 Word 就从头写。先用 3 级标题搭骨架：背景、问题、方案、风险、下一步。骨架清晰，内容才会清晰。" },
    { id:"ot27", emoji:"🤝", category:"沟通技巧", title:"汇报用 PREP 结构",                  content:"Point（结论）→ Reason（原因）→ Example（例子）→ Point（重申结论）。30 秒把事说清楚，领导最爱这种表达。" },
    { id:"ot28", emoji:"📊", category:"Excel 技巧", title:"条件格式让数据自己说话",            content:"选中数据 → 开始 → 条件格式 → 数据条/色阶。关键数值高低一目了然，不用一个个看数字。" },
    { id:"ot29", emoji:"🔒", category:"安全习惯", title:"敏感文件加水印 + 只读",             content:"对外发的报价、方案 PDF 加上「仅供 XX 公司参考」水印，并设置只读/禁止编辑。减少信息泄露和恶意修改风险。" },
    { id:"ot30", emoji:"📱", category:"效率神器", title:"微信文件 3 天内会过期",             content:"重要文件收到后立刻转存到云盘或本地。微信未下载文件 3 天后自动过期，等要用时找不到会很被动。" }
  ]
};
